using Generated.Client;
using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;

namespace Enea_WPF;

public partial class UserListPage : UserControl
{
    private readonly MyApiClient _apiClient;
    private readonly IServiceProvider _serviceProvider;

    public UserListPage(MyApiClient apiClient, IServiceProvider sp)
    {
        _apiClient = apiClient;
        _serviceProvider = sp;
        Users = new ObservableCollection<UserReadDto>();
        DataContext = this;
        InitializeComponent();
    }
    public ObservableCollection<UserReadDto> Users { get; set; }



    public async void LoadUsers()
    {
        try
        {
            var users = await _apiClient.UserGET2Async(0, 0);
            Users.Clear();
            foreach (var user in users.Items)
            {
                Users.Add(user);
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show($"Failed to load users: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        dataGridUsers.Items.Refresh();
    }

    private async void CreateUserButton_Click(object sender, RoutedEventArgs e)
    {
        var modal = new UserModal(_apiClient);
        if (modal.ShowDialog() == true)
        {
            LoadUsers();
        }
    }

    private async void EditUserButton_Click(object sender, RoutedEventArgs e)
    {
        if (dataGridUsers.SelectedItem is UserReadDto selectedUser)
        {
            var modal = new UserModal(_apiClient, selectedUser);
            if (modal.ShowDialog() == true)
            {
                LoadUsers();
            }
        }
        else
        {
            MessageBox.Show("Please select a user to edit.", "Warning", MessageBoxButton.OK, MessageBoxImage.Warning);
        }
    }

    private async void DeleteUserButton_Click(object sender, RoutedEventArgs e)
    {
        if (dataGridUsers.SelectedItem is UserReadDto selectedUser)
        {
            var result = MessageBox.Show($"Are you sure you want to delete the user '{selectedUser.Name}'?",
                "Confirm Delete",
                MessageBoxButton.YesNo,
                MessageBoxImage.Warning);

            if (result == MessageBoxResult.Yes)
            {
                try
                {
                    await _apiClient.UserDELETEAsync(selectedUser.Id);
                    Users.Remove(selectedUser);
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Failed to delete user: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }
        else
        {
            MessageBox.Show("Please select a user to delete.", "Warning", MessageBoxButton.OK, MessageBoxImage.Warning);
        }
    }

    private void DataGridUsers_OnAutoGeneratedColumns(object? sender, EventArgs e)
    {
        // set id as first column
        var idColumn = dataGridUsers.Columns.FirstOrDefault(c => c.Header.ToString() == "Id");

        if (idColumn != null)
        {
            dataGridUsers.Columns.Remove(idColumn);
            dataGridUsers.Columns.Insert(0, idColumn);
        }
    }
}